mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views
from .views import EventList, EventDetail


app_name = 'polls'
urlpatterns = [
    path('events/', views.index, name='index'),
    path('<int:event_id>/', views.detail, name='detail'),
    path('events/create', views.new_event, name='create'),

    # path("events/", views.IndexView.as_view(), name="event_list"),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

mysite/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Event(models.Model):
    event_name = models.CharField(max_length=200)
    event_date = models.DateField('event date')


class Event_Item(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    item_text = models.CharField(max_length=200)
    item_time = models.TimeField('Start time')

    class Meta:
        db_table = "items"

mysite/polls/forms.py
from django.forms import ModelForm
from .models import Event

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['event_name', 'event_date']

mysite/polls/views.py
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from .models import Event, Event_Item
from .serializers import EventSerializer
from . import forms

def index(request):
    event_list = Event.objects.order_by('-event_date')[:5]
    context = {
        'event_list': event_list,
    }
    return render(request, 'events/index.html', context)

def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event_item = Event_Item.objects.filter(event=event)
    context = {
        'event': event,
        'event_item': event_item
    }
    return render(request, 'events/detail.html', context)

def new_event(request):
    if request.method == 'POST':
        form = forms.EventForm(request.POST)
        if form.is_valid():
            event = Event(event_name=form.cleaned_data["event_name"], event_date=form.cleaned_data["event_date"])
            event.save()
            return redirect('polls:index')
    elif request.method == 'GET':
        form = forms.EventForm()
        return render(request, 'events/new_event.html', {'form': form})





class EventList(APIView):
    def get(self, request):
        events = Event.objects.all()[:20]
        data = EventSerializer(events, many=True).data
        return render(request, 'events/index.html', {'latest_event_list': data})


class EventDetail(viewsets.ViewSet):
    def list(self, request, event_id):
        event = Event.objects.get(id=event_id)
        data = EventSerializer(event).data
        return render(request, 'events/detail.html', {'event': data})

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

mysite/polls/templates/events/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}">

<div class="custom-padding">
  <nav>
    <div class="logo">Event Planner</div>

    <ul class="menu-area">
      <li><a href="{% url 'polls:index' %}">All Events</a></li>
      <li><a href="#">Add Event</a></li>
    </ul>
  </nav>
</div>


<h1 id="eventdetail">{{ event.event_name }}</h1>


{% for item in event_item %}
    <li id="eventitems">{{ item.item_text }} | Starting at: {{ item.item_time }}</li>
{% endfor %}

mysite/polls/templates/events/index.html
<!-- Template from https://codepen.io/divinector/pen/qgZKYQ -->


{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}">

<div class="custom-padding">
  <nav>
    <div class="logo">Event Planner</div>

    <ul class="menu-area">
      <li><a href="{% url 'polls:index' %}">All Events</a></li>
      <li><a href="{% url 'polls:create' %}">Add Event</a></li>
    </ul>
  </nav>
</div>


<div class="row">
    <br>
    <div class="col-sm-6 col-sm-offset-3">
            {% if event_list %}
                <ul id="eventlist">
                {% for event in event_list %}
                <li id="eventitems"><a href="{% url 'polls:detail' event.id %}">{{ event.event_name }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No events are available.</p>
            {% endif %}
        </div>
</div>

mysite/polls/templates/events/new_event.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}">

<div class="custom-padding">
  <nav>
    <div class="logo">Event Planner</div>

    <ul class="menu-area">
      <li><a href="{% url 'polls:index' %}">All Events</a></li>
    </ul>
  </nav>
</div>

<div id="customdiv">
    <form action="{% url 'polls:create'%}" method="post">
        {% csrf_token %}
        {{form}}

        <<input type="submit"  value="create">
    </form>
</div>